run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # strange
    - gci
    - goimports
    - tagliatelle
    - wrapcheck
    # debatable
    - depguard
    - dupl
    - exhaustruct
    - goconst
    - godot
    - godox
    - gomnd
    - gosec
    - ireturn
    - nilnil
    - noctx
    - nonamedreturns
    - paralleltest
    - tagalign
    - testpackage
    - varnamelen
    - wsl
    # other reasons
    - cyclop   # gocognit  do the same
    - funlen   # gocognit  do the same
    - goerr113 # errorlint do the same
    - gocyclo  # gocognit  do the same
    - maintidx # gocognit  do the same
