run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # deprecated
    - tenv
    - goerr113
    # strange
    - gci
    - goimports
    - tagliatelle
    - wrapcheck
    # debatable
    - depguard
    - dupl
    - exhaustruct
    - goconst
    - godot
    - godox
    - gosec
    - ireturn
    - nilnil
    - noctx
    - nonamedreturns
    - paralleltest
    - tagalign
    - testpackage
    - varnamelen
    - wsl
    - gofumpt
    - mnd
    # other reasons
    - cyclop   # gocognit  do the same
    - funlen   # gocognit  do the same
    - gocyclo  # gocognit  do the same
    - maintidx # gocognit  do the same
